version: '3.7'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MAGENTO_DB_NAME}
      MYSQL_USER: ${MAGENTO_DB_USER}
      MYSQL_PASSWORD: ${MAGENTO_DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2
    ports:
      - "${REDIS_PORT}:6379"

  opensearch:
    image: opensearchproject/opensearch:1.2.4
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    ports:
      - "${OPENSEARCH_PORT}:9200"

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - ./magento:/var/www/html
    environment:
      COMPOSER_HOME: /tmp
    depends_on:
      - db
      - redis
      - opensearch
    ports:
      - "9000:9000"

  web:
    image: nginx:1.21-alpine
    depends_on:
      - php
    volumes:
      - ./magento:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

volumes:
  db-data:
  opensearch-data:
